genefamilies:
  table_name: genefamilies
  description: 'HUMAnN: genefamilies (out_genefamilies.tsv.gz)'
  input_path_suffix: /humann/out_genefamilies.tsv.gz
  columns:
    gene_family: VARCHAR
    rpk_abundance: DOUBLE
  header:
    humann_header: 1
  columns_to_split:
    gene_family:
      delimiter: '[|.]'
      parts:
        gene_family_uniref: 1
        gene_family_genus: 2
        gene_family_species: 3
  columns_to_sort:
    - uuid
    - gene_family_species

genefamilies_cpm:
  table_name: genefamilies_cpm
  description: 'HUMAnN: genefamilies_cpm (out_genefamilies_cpm.tsv.gz)'
  input_path_suffix: /humann/out_genefamilies_cpm.tsv.gz
  columns:
    gene_family: VARCHAR
    rpk_abundance: DOUBLE
  header:
    humann_header: 1
  columns_to_split:
    gene_family:
      delimiter: '[|.]'
      parts:
        gene_family_uniref: 1
        gene_family_genus: 2
        gene_family_species: 3
  columns_to_sort:
    - uuid
    - gene_family_species

genefamilies_cpm_stratified:
  table_name: genefamilies_cpm_stratified
  description: 'HUMAnN: genefamilies_cpm_stratified (out_genefamilies_cpm_stratified.tsv.gz)'
  input_path_suffix: /humann/out_genefamilies_cpm_stratified.tsv.gz
  columns:
    gene_family: VARCHAR
    rpk_abundance: DOUBLE
  header:
    humann_header: 1
  columns_to_split:
    gene_family:
      delimiter: '[|.]'
      parts:
        gene_family_uniref: 1
        gene_family_genus: 2
        gene_family_species: 3
  columns_to_sort:
    - uuid
    - gene_family_species

genefamilies_cpm_unstratified:
  table_name: genefamilies_cpm_unstratified
  description: 'HUMAnN: genefamilies_cpm_unstratified (out_genefamilies_cpm_unstratified.tsv.gz)'
  input_path_suffix: /humann/out_genefamilies_cpm_unstratified.tsv.gz
  columns:
    gene_family: VARCHAR
    rpk_abundance: DOUBLE
  header:
    humann_header: 1
  columns_to_split:
  columns_to_sort:
    - uuid
    - gene_family

genefamilies_relab:
  table_name: genefamilies_relab
  description: 'HUMAnN: genefamilies_relab (out_genefamilies_relab.tsv.gz)'
  input_path_suffix: /humann/out_genefamilies_relab.tsv.gz
  columns:
    gene_family: VARCHAR
    rpk_abundance: DOUBLE
  header:
    humann_header: 1
  columns_to_split:
    gene_family:
      delimiter: '[|.]'
      parts:
        gene_family_uniref: 1
        gene_family_genus: 2
        gene_family_species: 3
  columns_to_sort:
    - uuid
    - gene_family_species

genefamilies_relab_stratified:
  table_name: genefamilies_relab_stratified
  description: 'HUMAnN: genefamilies_relab_stratified (out_genefamilies_relab_stratified.tsv.gz)'
  input_path_suffix: /humann/out_genefamilies_relab_stratified.tsv.gz
  columns:
    gene_family: VARCHAR
    rpk_abundance: DOUBLE
  header:
    humann_header: 1
  columns_to_split:
    gene_family:
      delimiter: '[|.]'
      parts:
        gene_family_uniref: 1
        gene_family_genus: 2
        gene_family_species: 3
  columns_to_sort:
    - uuid
    - gene_family_species

genefamilies_relab_unstratified:
  table_name: genefamilies_relab_unstratified
  description: 'HUMAnN: genefamilies_relab_unstratified (out_genefamilies_relab_unstratified.tsv.gz)'
  input_path_suffix: /humann/out_genefamilies_relab_unstratified.tsv.gz
  columns:
    gene_family: VARCHAR
    rpk_abundance: DOUBLE
  header:
    humann_header: 1
  columns_to_split:
  columns_to_sort:
    - uuid
    - gene_family

genefamilies_stratified:
  table_name: genefamilies_stratified
  description: 'HUMAnN: genefamilies_stratified (out_genefamilies_stratified.tsv.gz)'
  input_path_suffix: /humann/out_genefamilies_stratified.tsv.gz
  columns:
    gene_family: VARCHAR
    rpk_abundance: DOUBLE
  header:
    humann_header: 1
  columns_to_split:
    gene_family:
      delimiter: '[|.]'
      parts:
        gene_family_uniref: 1
        gene_family_genus: 2
        gene_family_species: 3
  columns_to_sort:
    - uuid
    - gene_family_species

genefamilies_unstratified:
  table_name: genefamilies_unstratified
  description: 'HUMAnN: genefamilies_unstratified (out_genefamilies_unstratified.tsv.gz)'
  input_path_suffix: /humann/out_genefamilies_unstratified.tsv.gz
  columns:
    gene_family: VARCHAR
    rpk_abundance: DOUBLE
  header:
    humann_header: 1
  columns_to_split:
  columns_to_sort:
    - uuid
    - gene_family

pathabundance:
  table_name: pathabundance
  description: 'HUMAnN: pathabundance (out_pathabundance.tsv.gz)'
  input_path_suffix: /humann/out_pathabundance.tsv.gz
  columns:
    pathway: VARCHAR
    abundance: DOUBLE
  header:
    humann_header: 1
  columns_to_split:
    pathway:
      delimiter: '[|.]'
      parts:
        pathway_uniref: 1
        pathway_genus: 2
        pathway_species: 3
  columns_to_sort:
    - uuid
    - pathway_species

pathabundance_cpm:
  table_name: pathabundance_cpm
  description: 'HUMAnN: pathabundance_cpm (out_pathabundance_cpm.tsv.gz)'
  input_path_suffix: /humann/out_pathabundance_cpm.tsv.gz
  columns:
    pathway: VARCHAR
    abundance: DOUBLE
  header:
    humann_header: 1
  columns_to_split:
    pathway:
      delimiter: '[|.]'
      parts:
        pathway_uniref: 1
        pathway_genus: 2
        pathway_species: 3
  columns_to_sort:
    - uuid
    - pathway_species

pathabundance_relab:
  table_name: pathabundance_relab
  description: 'HUMAnN: pathabundance_relab (out_pathabundance_relab.tsv.gz)'
  input_path_suffix: /humann/out_pathabundance_relab.tsv.gz
  columns:
    pathway: VARCHAR
    abundance: DOUBLE
  header:
    humann_header: 1
  columns_to_split:
    pathway:
      delimiter: '[|.]'
      parts:
        pathway_uniref: 1
        pathway_genus: 2
        pathway_species: 3
  columns_to_sort:
    - uuid
    - pathway_species

pathabundance_stratified:
  table_name: pathabundance_stratified
  description: 'HUMAnN: pathabundance_stratified (out_pathabundance_stratified.tsv.gz)'
  input_path_suffix: /humann/out_pathabundance_stratified.tsv.gz
  columns:
    pathway: VARCHAR
    abundance: DOUBLE
  header:
    humann_header: 1
  columns_to_split:
    pathway:
      delimiter: '[|.]'
      parts:
        pathway_uniref: 1
        pathway_genus: 2
        pathway_species: 3
  columns_to_sort:
    - uuid
    - pathway_species

pathabundance_unstratified:
  table_name: pathabundance_unstratified
  description: 'HUMAnN: pathabundance_unstratified (out_pathabundance_unstratified.tsv.gz)'
  input_path_suffix: /humann/out_pathabundance_unstratified.tsv.gz
  columns:
    pathway: VARCHAR
    abundance: DOUBLE
  header:
    humann_header: 1
  columns_to_split:
  columns_to_sort:
    - uuid
    - pathway

pathabundance_cpm_stratified:
  table_name: pathabundance_cpm_stratified
  description: 'HUMAnN: pathabundance_cpm_stratified (out_pathabundance_cpm_stratified.tsv.gz)'
  input_path_suffix: /humann/out_pathabundance_cpm_stratified.tsv.gz
  columns:
    pathway: VARCHAR
    abundance: DOUBLE
  header:
    humann_header: 1
  columns_to_split:
    pathway:
      delimiter: '[|.]'
      parts:
        pathway_uniref: 1
        pathway_genus: 2
        pathway_species: 3
  columns_to_sort:
    - uuid
    - pathway_species

pathabundance_relab_stratified:
  table_name: pathabundance_relab_stratified
  description: 'HUMAnN: pathabundance_relab_stratified (out_pathabundance_relab_stratified.tsv.gz)'
  input_path_suffix: /humann/out_pathabundance_relab_stratified.tsv.gz
  columns:
    pathway: VARCHAR
    abundance: DOUBLE
  header:
    humann_header: 1
  columns_to_split:
    pathway:
      delimiter: '[|.]'
      parts:
        pathway_uniref: 1
        pathway_genus: 2
        pathway_species: 3
  columns_to_sort:
    - uuid
    - pathway_species

pathabundance_cpm_unstratified:
  table_name: pathabundance_cpm_unstratified
  description: 'HUMAnN: pathabundance_cpm_unstratified (out_pathabundance_cpm_unstratified.tsv.gz)'
  input_path_suffix: /humann/out_pathabundance_cpm_unstratified.tsv.gz
  columns:
    pathway: VARCHAR
    abundance: DOUBLE
  header:
    humann_header: 1
  columns_to_split:
  columns_to_sort:
    - uuid
    - pathway

pathabundance_relab_unstratified:
  table_name: pathabundance_relab_unstratified
  description: 'HUMAnN: pathabundance_relab_unstratified (out_pathabundance_relab_unstratified.tsv.gz)'
  input_path_suffix: /humann/out_pathabundance_relab_unstratified.tsv.gz
  columns:
    pathway: VARCHAR
    abundance: DOUBLE
  header:
    humann_header: 1
  columns_to_split:
  columns_to_sort:
    - uuid
    - pathway

pathcoverage:
  table_name: pathcoverage
  description: 'HUMAnN: pathcoverage (out_pathcoverage.tsv.gz)'
  input_path_suffix: /humann/out_pathcoverage.tsv.gz
  columns:
    pathway: VARCHAR
    coverage: DOUBLE
  header:
    humann_header: 1
  columns_to_split:
    pathway:
      delimiter: '[|.]'
      parts:
        pathway_uniref: 1
        pathway_genus: 2
        pathway_species: 3
  columns_to_sort:
    - uuid
    - pathway_species

pathcoverage_stratified:
  table_name: pathcoverage_stratified
  description: 'HUMAnN: pathcoverage_stratified (out_pathcoverage_stratified.tsv.gz)'
  input_path_suffix: /humann/out_pathcoverage_stratified.tsv.gz
  columns:
    pathway: VARCHAR
    coverage: DOUBLE
  header:
    humann_header: 1
  columns_to_split:
    pathway:
      delimiter: '[|.]'
      parts:
        pathway_uniref: 1
        pathway_genus: 2
        pathway_species: 3
  columns_to_sort:
    - uuid
    - pathway_species

pathcoverage_unstratified:
  table_name: pathcoverage_unstratified
  description: 'HUMAnN: pathcoverage_unstratified (out_pathcoverage_unstratified.tsv.gz)'
  input_path_suffix: /humann/out_pathcoverage_unstratified.tsv.gz
  columns:
    pathway: VARCHAR
    coverage: DOUBLE
  header:
    humann_header: 1
  columns_to_split:
  columns_to_sort:
    - uuid
    - pathway